#!/bin/sh
#Look for a local pre-commit hook in the repository
if [ -x .git/hooks/pre-commit ]; then
    .git/hooks/pre-commit || exit $?
fi
trufflehog git file://. --since-commit HEAD --only-verified --fail --no-update > trufflehog_output.json
if [ -s trufflehog_output.json ]
then
    cat trufflehog_output.json
    rm trufflehog_output.json
    echo "TruffleHog found secrets. Aborting commit. use --no-verify to bypass it"
    exit 2
fi
rm trufflehog_output.json
